### ISSUE TITLE
Remove infinite scroll, or change the way scroll position is handled

### ISSUE THREAD

**Issue by megalon** [lolPants/beatsaver-reloaded#10]
## Platform
**This feature request concerns:** *(select all that apply)*
- [x] Client
- [ ] Server

## Details
**Please describe the requested feature in as much detail as possible:**
Whenever you click on a link in a list of maps, it takes you to the details page for that map. When you then go back to the list, it returns you to the top of the list instead of your scroll position.

No matter if you are viewing the "Latest" list, looking at a particular users' uploads, or looking at search results, as soon as you click on a link you have completely lost your scroll position and have to scroll back to it if you want to pick up where you left off.

There are no download buttons when you are viewing a list, so you have to view the details to download a map, or read the description.

Middle click also *does not* open the link in a new window, so there is no way to get around this.

## Preferred Solution
Pagination seems like the best solution here. You can simply return to the previous page you were looking at, similar to how BeatSaver used to work.

Also, being able to middle click and open a window in a new tab is always helpful.

**Comment by lolPants** [comment]
Middle click was added by #9

**Comment by n3tman** [comment]
+1 for removing:

- it's bad UX, there should always be an option to disable it
- you're not changing the hashes, there's no way to share the link to current page (unless you open dev console and copy XHR link)
- website footer is inaccessible
- separate [extensions](https://chrome.google.com/webstore/detail/autopagerize/igiofjhpmpihnifddepnpngfjhkfenbp) exist for those who like infinite scroll everywhere

**Comment by lolPants** [comment]
@n3tman why would you want a permalink to an arbitrary point in a constantly changing list?

**Comment by n3tman** [comment]
@lolPants 

Some lists aren't constantly changing (e.g. sorted by Downloads/Plays, or maybe Oldest - would be great to have it).
Also even though links to Latest maps are changing, they are valid for a certain period of time, so still can be shared.

Another problem is you're making a drastic change to user experience which is generally a bad idea (I'm creating a separate issue for this).

**Comment by telos00** [comment]
Yes please remove infinite scroll, or make a way to jump to a particular entry.

**Comment by lolPants** [comment]
The rest of infinite scroll handling is being tracked on #24
