### ISSUE TITLE
Upload simply returns 502 Something Went Wrong

### ISSUE THREAD

**Issue by nolanblew** [lolPants/beatsaver-reloaded#101]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
Trying to upload new map through BeatSaver results in 502, and the only info I get in the UI is the message: "Beatsaver ZIP: Something went wrong! Try again later." No idea what the issue is (maybe my ZIP file?) But I have no idea how to figure out _what_ the issue is.

![image](https://user-images.githubusercontent.com/1565705/102187075-6069cf00-3e68-11eb-8979-1c64e87a1e48.png)

![image](https://user-images.githubusercontent.com/1565705/102187201-87c09c00-3e68-11eb-84a2-2582fda6cc4c.png)

## Reproducing the Problem
Attempt to upload the new map through beatsaver reloaded. I would expect to upload to process, and if there was a problem to tell me what the problem is (or at least link me to a guide). A 502 seems like a server/gateway issue, so if this is unrelated to this repo itself (and on the implementation) then disregard and close this PR.

**Comment by Isoware** [comment]
They have troubles with servers since some days, I think they are currently trying to solve it.

**Comment by firerm** [comment]
We waiting for the fix ... it's since 12 December 2020 but Yesterday someone upload a map ...

**Comment by luludotdev** [comment]
This codebase does not serve any 502 errors on upload, this problem is upstream and relies on the people running `beatsaver.com` to solve.

**Comment by nolanblew** [comment]
@lolPants I suspected so but just wanted the clarification. Thanks 👍
