### ISSUE TITLE
How do delete an account or re-send validation email

### ISSUE THREAD

**Issue by revelcw** [lolPants/beatsaver-reloaded#102]
Hey everyone, I need help. I tried to create an account to upload songs, but I did it in the [Google outage](https://www.theverge.com/2020/12/15/22176958/google-gmail-errors-down-outage-stadia) time. Therefore, I didn't get an email to verify my account. Also, I put in my password wrong, and there's no way to change it, so another strike. Anyway, is there a fix this? Thank you, revelcw. 

![image](https://user-images.githubusercontent.com/29359616/102287755-12f16e80-3f09-11eb-9c91-f59e826b8873.png)

![image](https://user-images.githubusercontent.com/29359616/102287850-47fdc100-3f09-11eb-8ef5-7aa1e121cdf4.png)

**Comment by luludotdev** [comment]
![image](https://user-images.githubusercontent.com/2358182/96707383-b30a9b80-138f-11eb-89ec-808647898b73.png)

Contact the people who run beatsaver.com
