### ISSUE TITLE
Didn't get a verification E-Mail.

### ISSUE THREAD

**Issue by SteffoSpieler** [lolPants/beatsaver-reloaded#104]
## Platform
**This bug report concerns:**
- [ ] Client
- [x] Server

## Details
I got no verification E-Mail.

## Reproducing the Problem
1. Create a account on beatsaver.com.
2. Get no E-Mail.

**Comment by luludotdev** [comment]
![image](https://user-images.githubusercontent.com/2358182/96707383-b30a9b80-138f-11eb-89ec-808647898b73.png)

Contact the people who run beatsaver.com
