### ISSUE TITLE
Levels

### ISSUE THREAD

**Issue by BoogieHasFun** [lolPants/beatsaver-reloaded#107]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
**Please describe the problem you are having in as much detail as possible:**
When I open songs it doesn't load them at all! What could be the cause? 
## Reproducing the Problem
??

## Further Detail

**Comment by veltower** [comment]
Currently, the servers for Beat Saber and the Beat Saver website are down. Any updates on administration getting this fixed?

**Comment by BoogieHasFun** [comment]
They are still down, I'll keep waiting.

**Comment by PhJu** [comment]
According to the Beat Saber Modding Discord:

> **The Jellyfish#6936** yesterday at 19:25 GMT
>
> Greetings land dwellers and API scrapers, we've returned to the surface to make a brief announcement regarding the BeatSaver API. Our machines have been getting hit by the holidays as expected, but API abuse via scraping has been hitting harder than anything else lately. Some bad actors have been scraping the entire dataset (even after being limited), and randomizing user agents and IPs to circumvent our measures. As we don't have time to deal with this, we've taken down the entire API until we have an opportunity to find a solution. Please enjoy the rest of the holidays, and thank you for your attention.
> 
> To anyone hosting mirrors or scraping the entire dataset for any reason: please refrain from doing so until further notice. Anyone caught doing so, unless specifically allowed by us, will be subject to API bans. Additionally, to the party deliberately circumventing our API restrictions: stop doing so as you are ruining it for everyone.

**Comment by luludotdev** [comment]
As this has nothing to do with this repo, as has been stated many times I do not operate beatsaver.com, I shall be closing and locking this thread.
