### ISSUE TITLE
Song Unavailable

### ISSUE THREAD

**Issue by ghost** [lolPants/beatsaver-reloaded#109]
## Platform
**This bug report concerns:** *(select all that apply)*
- [x] Client
- [x] Server

## Details
**Please describe the problem you are having in as much detail as possible:**
unable to find songs
## Reproducing the Problem
**Please include detailed steps to reproduce the problem:**
enter the site and search with any amount of letters
Please recognise i have deleted the tab and refreshed 
![image](https://user-images.githubusercontent.com/74470480/103421607-30733900-4b95-11eb-8d6e-452f9d32cac7.png)

**Comment by luludotdev** [comment]
Dupe of #107

**Comment by ghost** [comment]
ah didnt notice it sorry
