### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by AlissaTheMetalFan** [lolPants/beatsaver-reloaded#111]
I am making some beat maps and I am wanting to upload them to beatsaver. I was filling out the username, email, and password and I clicked the register button and nothing happens. I don't know what to do. Can anybody help me?

**Comment by Sanic-69** [comment]
The Servers are down I think. I cant log in since wednesday

**Comment by Otter-man** [comment]
https://github.com/lolPants/beatsaver-reloaded/issues/107#issuecomment-752659243

**Comment by luludotdev** [comment]
Another dupe.
