### ISSUE TITLE
Unauthorized on map download

### ISSUE THREAD

**Issue by hendrikbl** [lolPants/beatsaver-reloaded#123]
When trying to download a map via the api endpoint `https://beatsaver.com/api/download/key/` i get an `401: Unauthorized` response.
This happens from curl and Powershell as well as from Node.js.

If I paste the address in my browser (Chrome) it works just fine.

I'm a little confused why this is happening. I've tried setting different user agents and accept headers but with no luck.

I'm not even sure if thats related to the implementation or the server beatsaver is currently running on.

**Comment by MoyuScript** [comment]
Try to set header 'Accept-Language'
