### ISSUE TITLE
having problem when trying to download side songs for beat saber via beat saver is BMBF

### ISSUE THREAD

**Issue by militarypotato** [lolPants/beatsaver-reloaded#126]
Everytime I get into beat saver via BMBF im getting the massage, "Not everything is finished yet with the rewrite, please be patient.
" What should I do?
![Capture](https://user-images.githubusercontent.com/83128823/115963379-b3931300-a527-11eb-8595-2e3104d3479a.PNG)

**Comment by SoCuul** [comment]
It always says this

**Comment by AshuraTDH** [comment]
> It always says this

YEAH, it was just my imagination that 40 hours earlier I can enter to bsaber,com and upload\download songs, and now I can't because of this message on main page, where I get redirected from any link
Is this what you mean?

**Comment by SoCuul** [comment]
> 
> 
> > It always says this
> 
> YEAH, it was just my imagination that 40 hours earlier I can enter to bsaber,com and upload\download songs, and now I can't because of this message on main page, where I get redirected from any link
> Is this what you mean?

Bsaber got infected with malware, and I'm pretty sure that it now redirects to a broken BeatSaver.
If you want to download songs, go to beatsaver.com

**Comment by AshuraTDH** [comment]
> If you want to download songs, go to beatsaver.com

That's just the site that you already said is broken (yes, I DID ctrl+c\ctrl+v). Screenshot from head post is from the broken beatsaver.com, bsaber redirects to a broken beatsaver.com. 
That is just the problem that brought us all here. Everything is broken. Even my nerves. A bit.
