### ISSUE TITLE
UI of map listing/details should be consistent with previous version (UX problems)

### ISSUE THREAD

**Issue by n3tman** [lolPants/beatsaver-reloaded#13]
## Platform
**This feature request concerns:**
- [x] Client
- [ ] Server

## Details
People who've been using BeatSaver daily for many months shouldn't be forced to adapt to author's view of where certain info is currently displayed, as well as to missing behaviors.

Visual comparison:

- Listing:
— before ([webarchive page](https://web.archive.org/web/20190503175334/https://beatsaver.com/browse/newest))
![bs_listing_old](https://user-images.githubusercontent.com/16892631/59563318-f1c46f00-9040-11e9-8e5b-cce69b1a0942.png)
— after
![bs_listing_new](https://user-images.githubusercontent.com/16892631/59563319-f25d0580-9040-11e9-849e-307221ae2f19.png)
- Details:
— before ([webarchive page](https://web.archive.org/web/20190506232952/https://beatsaver.com/browse/detail/16043-17424))
![bs_details_old](https://user-images.githubusercontent.com/16892631/59563370-dad24c80-9041-11e9-8623-0f4a08de5ba1.png)
— after
![bs_details_new](https://user-images.githubusercontent.com/16892631/59563371-dad24c80-9041-11e9-8cd4-26a71c032167.png)

Problems I see:
1. Crucial map info (number of downloads, likes and dislikes) is pushed to the right side, making it harder to understand if a certain map is worth checking or not based on metadata (need to move your eyes or head each time). Considering the increasing amount of maps posted, you can't say this info is "secondary" in nature. Also there's an empty space above difficulties anyway.
1. Listing: there's no download link on map card
1. Listing: whole map card is clickable, which makes it impossible to copy (and search in google, for example) song/artist name, map ID, author name or any other metadata without opening details page. Before there were 3 ways to go to Details page: clicking on map name, cover image and Details button, so you could easily explore maps without extra clicks.
1. Details: map cover as a background is kinda useless
## Preferred Solution
1. Move map stats close to map title/uploader and cover image:
&nbsp;
![bs_details_move](https://user-images.githubusercontent.com/16892631/59563738-94cbb780-9046-11e9-8b31-a1b7449c71e5.png)
1. Add download links to map card on listing page
1. Make map title/cover clickable instead of the whole card
1. Display cover image separately on details page, preferably with an increased size (compared to listing - as an improvement)

**Comment by lolPants** [comment]
All of the points raised here that I agree with have now been implemented
