### ISSUE TITLE
Mobile UI optimisation and improvement

### ISSUE THREAD

**Issue by n3tman** [lolPants/beatsaver-reloaded#14]
## Platform
**This feature request concerns:**
- [x] Client
- [ ] Server

## Details
Would be nice to give mobile users some love by adding responsive styles.

Current screens from BrowserStack:
- Listing
![2019-06-16_153723](https://user-images.githubusercontent.com/16892631/59564529-a4e89480-9050-11e9-9008-e4c538b24b10.png)
- Details 1
![2019-06-16_153745](https://user-images.githubusercontent.com/16892631/59564530-a4e89480-9050-11e9-9b01-292dc1421398.png)
- Details 2
![2019-06-16_153807](https://user-images.githubusercontent.com/16892631/59564531-a4e89480-9050-11e9-98b9-eca768772631.png)

## Preferred Solution
Make mobile styles user-friendly:
- don't squish cover images (maintain aspect ratio)
- adjust fonts
- move blocks
- set multi-column layout to single-column
- resize all cover images through cdn (?) to decrease traffic
- etc.

**Comment by lolPants** [comment]
Partially fixed as of a0703cb68c0ad469a3cdff3d9b84c24cca4d6e11
