### ISSUE TITLE
Some songs are missing?

### ISSUE THREAD

**Issue by BehnamMabodi** [lolPants/beatsaver-reloaded#18]
I used to download a song named "What you know" mapped by BennyDabeast from this [URL](https://beatsaver.com/details.php?id=1107):

Now it has a 404 error    
Is this a bug of new system? or this song is removed by someone?    
I'm sure the URL is correct

**Comment by lolPants** [comment]
Not all maps got migrated, old versions of maps were skipped due to technical constraints. Any maps that failed to convert were also skipped. If you know the original hash of the beatmap I can look into where it went. Without the map's hash there's not much I can do.

**Comment by n3tman** [comment]
Is there a log of what maps have been skipped? Would be nice to inform the mappers so they can reupload their content.

**Comment by skyzaq24** [comment]
@lolPants 
I don't have the hash of the song.     
So you are going to drop those songs completely? or it will convert in the future?

It would be nice to at least save old songs somewhere , and make a way to load legacy songs by same old method used before in SongCore plugin.    
or at least i can download and remap some of my favorites again. we can't drop them!

**Comment by BehnamMabodi** [comment]
@lolPants
I don't have the hash of the song.
So you are going to drop those songs completely? or it will convert in the future?

It would be nice to at least save old songs somewhere , and make a way to load legacy songs by same old method used before in SongCore plugin.
or at least i can download and remap some of my favorites again. we can't drop them!

**Comment by BehnamMabodi** [comment]
@n3tman can you search in the dump data by name?    
I doubt that anyone has hashmap of the songs. because that number was in the folder of the song. we don't have the song so we don't have the hashmap.

**Comment by lolPants** [comment]
You'll have to ask the operators of BeatSaver for that info. As stated in the readme I do not operate BeatSaver and this is just the code they use.
