### ISSUE TITLE
Add meta/OpenGraph tags to song pages to make Discord embeds nicer

### ISSUE THREAD

**Issue by n3tman** [lolPants/beatsaver-reloaded#19]
## Platform
**This feature request concerns:** *(select all that apply)*
- [x] Client
- [ ] Server

## Details
Previously embeds looked like this:

![bs-embeds](https://user-images.githubusercontent.com/16892631/59612101-34f80e00-9125-11e9-8a3e-ee8307f7e24a.png)

But now there's just a link, no info is fetched and embedded:

![bs-embed-now](https://user-images.githubusercontent.com/16892631/59612638-19d9ce00-9126-11e9-8324-096d930d4119.png)

## Preferred Solution
Add meta/OpenGraph tags to song pages. Here's a [tutorial](https://old.reddit.com/r/discordapp/comments/82p8i6/a_basic_tutorial_on_how_to_get_the_most_out_of/), for example.
Would be great to include uploader name and other useful stats too (difficulties, votes, etc).

**Comment by lolPants** [comment]
I'm going to politely ask you to stop asking for missing features. The project is still WIP.
This has already been added as of 14a62c27781d6a4192101584117b7190eb834258
