### ISSUE TITLE
beatsaver.com doesn't show precise upload timestamp of songs

### ISSUE THREAD

**Issue by telos00** [lolPants/beatsaver-reloaded#21]
## Platform
**This bug report concerns:** *(select all that apply)*
- [X] Client
- [ ] Server

## Details
Please display the exact upload timestamp instead of "4 hours ago" "3 days ago" etc.

## Reproducing the Problem
Go to https://beatsaver.com/browse/latest and look at the metadata. The songs have vague upload timestamps like "3 hours ago" or "4 days ago", which are useless when trying to figure out if the song is newer than the most recent song in my custom song folder.

**Comment by lolPants** [comment]
You can see the exact timestamps by hovering over the rough time
