### ISSUE TITLE
one click install with mod assistant used to work, now it doesn't

### ISSUE THREAD

**Issue by telos00** [lolPants/beatsaver-reloaded#22]
## Platform
**This bug report concerns:** *(select all that apply)*
- [X] Client
- [ ] Server

## Details
One Click Install with Mod Assistant was the easiest and fastest way to get a pile of songs on the old beatsaver.com. I hope it comes back ASAP.

## Reproducing the Problem
Go to https://beatsaver.com/browse/latest and look for the Oneclick install button. Nope, not there yet...

**Comment by lolPants** [comment]
This is coming back. Please do not report missing features as stated in #1
