### ISSUE TITLE
latest songs: no way to jump to a particular song index

### ISSUE THREAD

**Issue by telos00** [lolPants/beatsaver-reloaded#23]
## Platform
**This bug report concerns:** *(select all that apply)*
- [x] Client
- [ ] Server

## Details
There's no way to quickly jump to a particular song index with the current infinite scrolling list.

## Reproducing the Problem
Go to https://beatsaver.com/browse/latest. You used to be able to do something like https://beatsaver.com/browse/latest/200 to jump to the 200th newest song, but that doesn't work anymore.

**Comment by lolPants** [comment]
Duplicate of #10
