### ISSUE TITLE
Songs don't work in beat saber after the rewrite

### ISSUE THREAD

**Issue by jonny520** [lolPants/beatsaver-reloaded#26]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client 
- [ ] Server 

## Details
**Please describe the problem you are having in as much detail as possible:**
When I download songs and put them into the custom songs folder, it doesn't appear in the game,. even after I drag the beat saber.exe over the IPA. Something isn't right at all.
## Reproducing the Problem
**Please include detailed steps to reproduce the problem:**

## Further Detail
[Please include screenshots/browser info/anything else relevant]
[Otherwise delete this section]

**Comment by lolPants** [comment]
This is not a helpdesk. Go to the `#support` channel on the BSMG Discord server for help.
