### ISSUE TITLE
Unable to verify account

### ISSUE THREAD

**Issue by isaaclyman** [lolPants/beatsaver-reloaded#29]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client
- [X] Server

## Details
When I sign up for an account, the account verification email never comes through. As a result, I'm unable to upload new tracks.

## Reproducing the Problem
1. Create a new account using a gmail address.
2. The verification email never arrives.
3. https://beatsaver.com/user/upload says "You must verify your account before you can upload beatmaps. Check your email for a verification URL."

## Further Detail
I checked my spam folder and it's been over a week. Still no verification.

**Comment by lolPants** [comment]
![image](https://user-images.githubusercontent.com/2358182/60246137-02cd7580-98b6-11e9-819a-c46fb8f42ac0.png)

Perhaps you should take this up with the people who **do** operate prod BeatSaver.

**Comment by Herya** [comment]
> ![image](https://user-images.githubusercontent.com/2358182/60246137-02cd7580-98b6-11e9-819a-c46fb8f42ac0.png)
> 
> Perhaps you should take this up with the people who **do** operate prod BeatSaver.

Then who are they and how to contact them ?
Cause if the only website to upload songs is yours, and it link here, that's normal to come here to report bugs ...

**Comment by Herya** [comment]
> @Herya Is your email a hotmail/outlook email? I figured out the issue with the guy who runs beatsaver.com, and he had to manually verify my account because outlook/hotmail blocks emails from beatsaver for some reason. If anything, you can contact him on the modding discord (https://discord.gg/XCEZRWc) and he might be able to set your account as verified manually
> 
> His name is "Assistant" and he's an admin, so if he's online he's at the very top of the user list.

Thanks, I'll go to the discord when I have time, cause yes my email is a hotmail one for this account.
