### ISSUE TITLE
The search only finds full matches

### ISSUE THREAD

**Issue by narutards** [lolPants/beatsaver-reloaded#4]
The search on https://beatsaver.com/search will only find full words. Search for "Hatsune" and you'll find lots of songs by Hatsune Miku. But search for "Hatsu" and you will not find even a single song.

I'd expect the search to also find partial matches because you don't always know the full artist or song name or how to write it.

**Comment by lolPants** [comment]
This is due to the way MongoDB handles text searches, it's not great. I have plans to improve the search in the future but for now this is the best we've got.

**Comment by narutards** [comment]
Hmmm. I don't know what you are using now and I've not worked with MongoDB before (because, quite frankly, I think it sucks) but shouldnt regular expressions be able to do the job?

https://docs.mongodb.com/manual/reference/operator/query/regex/

**Comment by lolPants** [comment]
MongoDB has no way to perform regex searches on full text indexes (multi key search).
In future I'll be connecting MongoDB to Elasticsearch for much more powerful search.

**Comment by lolPants** [comment]
Closed as of b560c6f1bc815a22a877e0abea30b3a9587a61fc
