### ISSUE TITLE
Details area shrinks with more buttons on results page

### ISSUE THREAD

**Issue by Migushthe2nd** [lolPants/beatsaver-reloaded#41]
## Platform
**This bug report concerns:** *(select all that apply)*
- [x] Client
- [ ] Server

## (Further) Details
**Please describe the problem you are having in as much detail as possible:**
The text area is way smaller because of the buttons in the stats element.
![Screenshot_20190818-151007_Chrome](https://user-images.githubusercontent.com/22274715/63230816-556e4280-c212-11e9-8889-ba79809a0557.png)

**Comment by lolPants** [comment]
A rework of the mobile UI is something I'd like to do, but don't have the time for right now since most people use desktop.
