### ISSUE TITLE
No verification email

### ISSUE THREAD

**Issue by Herya** [lolPants/beatsaver-reloaded#43]
Hi,

I never received the verification email so I'm unable to upload any songs.

**Comment by isaaclyman** [comment]
See #29, you probably won't find help here. Let me know if you figure this one out though.

**Comment by isaaclyman** [comment]
Just signed up again with a different email and it worked this time. YMMV.

**Comment by Herya** [comment]
> Just signed up again with a different email and it worked this time. YMMV.

The point is to link up your account with beatsaber, so if you register with another email then your account is not linked.
