### ISSUE TITLE
Download button leads to main page

### ISSUE THREAD

**Issue by oksoff** [lolPants/beatsaver-reloaded#47]
## Platform
Web

## Details
`Download` button for song leads to https://beatsaver.com and not to song download

## Reproducing the Problem
Hover over download button

## Further Detail
Checked in both firefox and chrome

![image](https://user-images.githubusercontent.com/30262807/65309686-4114c100-db95-11e9-9d07-d7165ea9b23b.png)

**Comment by lolPants** [comment]
I can't reproduce this. I'm going to need a little more information (specific browser versions etc)
I tested on `Chrome 76.0.3809.123`

**Comment by oksoff** [comment]
Updated chromium from version 74.xx to 77.0.3865.75 and it works there.

Still doesn't work on Firefox 69.0.1 (latest version). I can totally believe its a problem on my end though.

Video:
https://streamable.com/dkpp5
1) Firefox 69.0.1 with addons enabled - no effect on pressing download button
2) Firefox 69.0.1 with addons disabled - no effect on pressing download button
3) Chromium 77.0.3865.75 - everything works as intended
4) One click install works in Firefox (shouldn't matter but it shows neighbor button works)

**Comment by lolPants** [comment]
I believe it's a slightly different issue than originally thought, as my testing on FF reveals the same thing.

I'll investigate further when I get home.
