### ISSUE TITLE
Another Download redirecting to the dashboard on Beatsaver

### ISSUE THREAD

**Issue by MisseurPotato** [lolPants/beatsaver-reloaded#48]
## Platform
**This bug report concerns:** 
- [x] Client

## Details
As shown with oksoffs problem, the download sends me to the main page. I'm on the most recent version of Chrome (77 and some decimals or so) and not sure why it would still be doing it, be it my end or the site. 

#47

**Comment by lolPants** [comment]
I can't reproduce this issue. Unless you can post reliable repro steps I'm gonna close this issue since the other one was fixed/
