### ISSUE TITLE
CORS Header inconsistently missing from CDN downloads

### ISSUE THREAD

**Issue by apmorton** [lolPants/beatsaver-reloaded#58]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client
- [X] Server

## Details
When using the API to download a map from another webpage (https://skystudioapps.com/bs-viewer/?id=1051 for example), occasionally the `access-control-allow-origin` header will be missing from the response to the cdn request, causing a CORS violation.

## Reproducing the Problem
I am not entirely sure how to reliably reproduce this issue, since it seems rather inconsistent.

I do however notice that the access-control-allow-origin header will not appear on a cdn response unless the request contains an origin header:
```
$ curl -s -H "Origin: http://example.com" -I https://beatsaver.com/cdn/1049/04d68717bfa11d8031ba470d760090a814602596.zip | grep allow-origin
access-control-allow-origin: *
$ curl -s -I https://beatsaver.com/cdn/1049/04d68717bfa11d8031ba470d760090a814602596.zip | grep allow-origin
$
```

Possibly there is some issue with cloudflare caching going on here?
The prudent thing to do would be to simply always supply `access-control-allow-origin: *` header on API/CDN responses.

## Further Detail
If I can reproduce this again I will update the issue with a HAR from chrome.

**Comment by lolPants** [comment]
This is a problem with deployment, something this repo does not cover. I would recommend forwarding this onto the people who *do* run BeatSaver.
