### ISSUE TITLE
Map difficulty metadata

### ISSUE THREAD

**Issue by BaliBalo** [lolPants/beatsaver-reloaded#6]
## Platform
**This feature request concerns:** *(select all that apply)*
- [ ] Client
- [x] Server (API)

## Details
The API used to provide for each difficulty informations like the duration (time of the last note), number of notes and number of obstacles.
Is there any plan to add that back?

## Preferred Solution
Having this data in the `metadata` field. Maybe an object containing the various properties instead of `true` in the `difficulties` object when the difficulty exists.

**Comment by lolPants** [comment]
If someone wants to submit a PR to add this, I'll accept it. Otherwise it's low down on the list of priorities.

**Comment by BaliBalo** [comment]
Totally understand. I might be able to work on a PR this weekend if you think this is a correct way to do it (having the informations as an object in the difficulties list instead of `true`).

**Comment by lolPants** [comment]
Not stale, being handled by #20

**Comment by lolPants** [comment]
Closed by #20
