### ISSUE TITLE
No verification e-mails

### ISSUE THREAD

**Issue by cdomergue** [lolPants/beatsaver-reloaded#62]
## Platform
**This bug report concerns:** *(select all that apply)*
- [X] Client
- [X] Server

## Details
When I create a new account, with a valid e-mail, I don't receive it in my Inbox nor in Spam.
I can't upload beatmap. 

## Reproducing the Problem
Create a new account with valid e-mail

## Further Detail
I've tried with two accounts, one in gmail and the other one in protonmail.
Accounts are Adraenor and Adraenor2

**Comment by lolPants** [comment]
This seems like a problem for the people who operate BeatSaver, which this repo clearly states is not me.
![image](https://user-images.githubusercontent.com/2358182/71703061-a39f6f00-2dca-11ea-879b-92292ac42b92.png)
