### ISSUE TITLE
API server not handling www subdomain in requests

### ISSUE THREAD

**Issue by shininghero** [lolPants/beatsaver-reloaded#63]
## Platform
**This bug report concerns:** *(select all that apply)*
- [X] Client
- [ ] Server

## Details
API server gives below error if request contains the www subdomain:

    404 Site www.beatsaver.com is not served on this interface

## Reproducing the Problem
Links in this format will work:

    http://beatsaver.com/api/download/key/32e

Links with the www will fail:

    http://www.beatsaver.com/api/download/key/32e

## Further Detail
![image](https://user-images.githubusercontent.com/17071843/71942501-70bef780-318b-11ea-9622-d2722115aae2.png)

**Comment by lolPants** [comment]
I do not operate beatsaver.com
