### ISSUE TITLE
BeatSaver website wont load songs to download

### ISSUE THREAD

**Issue by fourskillers** [lolPants/beatsaver-reloaded#64]
## Platform
**This bug report concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
When I try to download a song from the BeatSaver website the website is just loading but nothing happened. 

## Reproducing the Problem
I just have to try to get on a song as example: I click on the beatmap link https://beatsaver.com/beatmap/12f2 and nothing will happen an the site just loads
![97e89b15c9ac9888a990108b4311ff94](https://user-images.githubusercontent.com/59768566/72205621-93038e80-3485-11ea-9836-add05c861f2d.png)

**Comment by lolPants** [comment]
this is a known bug that was added in d099127d37eeb3a8301f33c492a9aeaf854d2c6b
as I don't have time to work on this, any PRs are welcome

**Comment by lolPants** [comment]
Closed as of 3b14104b558cdd170a8dfe9d233939dc1d61597b
