### ISSUE TITLE
Add CORS for ZIPs.

### ISSUE THREAD

**Issue by ngokevin** [lolPants/beatsaver-reloaded#7]
## Platform
**This feature request concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
**Please describe the requested feature in as much detail as possible:**
*Note if your feature request is related to a problem.*

The BeatSaver Viewer needs to be able to fetch and parse the ZIPs from JavaScript. The ZIPs no longer have access-control-allow-origin * headers so the Viewer cannot fetch and play the ZIPs.

## Preferred Solution
**Write a clear and concise description of what you want to happen:**

Add CORS headers on the ZIP files.

Will workaround with `https://cors-anywhere.herokuapp.com/` for now.

**Comment by lolPants** [comment]
This should be fixed now

**Comment by ngokevin** [comment]
Thanks!
