### ISSUE TITLE
Add support for RSS/Atom Feeds

### ISSUE THREAD

**Issue by pR0Ps** [lolPants/beatsaver-reloaded#73]
## Platform
**This feature request concerns:**
- [ ] Client
- [x] Server

## Details
The site currently does not provide RSS/Atom feeds (and I don't see any plans for it in the issue tracker). This makes it difficult to automatically follow new maps or certain uploaders.

## Preferred Solution
Add endpoints for newest and per-user Atom feeds and link them in the `<head>` section of the corresponding pages. See my work on the previous site backend: https://github.com/elliotttate/beatsaver-laravel/pull/39

**Comment by pR0Ps** [comment]
Still relevant

**Comment by pR0Ps** [comment]
Still relevant

**Comment by pR0Ps** [comment]
Still relevant

**Comment by lolPants** [comment]
RSS is an old standard and I don't see myself supporting it. Use the API if you want to follow new maps.
