### ISSUE TITLE
No Resend the confirm email, user cannot modify the own email address.

### ISSUE THREAD

**Issue by myfalcom** [lolPants/beatsaver-reloaded#75]
## Platform
**This feature request concerns:** *(select all that apply)*
-  Server

## Details
My account is registered and I tried to upload a map. The Website said that I have to confirm the url in my email. But there's no feature about to resend the mail or modify my email address. 
There's no personal account setting feature.

## Preferred Solution
Please add email url confirm resend option and personal account setting. Thank you.

**Comment by lolPants** [comment]
The real solution to this is to [contact the people who actually run BeatSaver](https://beatsaver.com/contact) (as I do not, as outlined clearly in this repo's readme) and ask them to setup mail correctly.

However this will become a non-issue pending the next major release as the verification is being changed.
