### ISSUE TITLE
/download/key works /download/hash does not

### ISSUE THREAD

**Issue by rubiksmaster02** [lolPants/beatsaver-reloaded#76]
Exactly as the title says
https://beatsaver.com/api/download/key/90e6 works
https://beatsaver.com/api/download/hash/914EDCFA17A8D7B1573F7FE8EB1B504CC7E47806 does not work

**Comment by lolPants** [comment]
BeatSaver hashes are lowercase hex

**Comment by rubiksmaster02** [comment]
That still is a problem, it should not be case sensitive. ESPECIALLY when the source ids are all caps

**Comment by lolPants** [comment]
All hashes presented by BeatSaver's API are lowercase.

**Comment by rubiksmaster02** [comment]
http://scoresaber.com/api.php?function=get-leaderboards&cat=3&page=1&limit=10&unique=1 not a single one of those is lowercase

**Comment by megalon** [comment]
That is the ScoreSaber API, not the BeatSaver API
