### ISSUE TITLE
I upload a song to beatsaver but i dont find it on beastsaber

### ISSUE THREAD

**Issue by Clapz100** [lolPants/beatsaver-reloaded#77]
I have recently been looking on how to make a song for beat saber and finally found a way to and I decided to upload it but when I upload it, it only showed up on beatsaver and I searched up the song name on beast saver and never found it.

Song Name: Skye - VOICES (feat. XXXTENTACION)

please help me

**Comment by lolPants** [comment]
BeastSaber periodically syncs from beatsaver.com, you just need to wait.

**Comment by Clapz100** [comment]
I have waited 12 hours and i still don't see it. do I have to wait for longer?

**Comment by lolPants** [comment]
I don't run BeastSaber so I have no idea. I suggest you ask in the [BSMG Discord](https://discord.gg/beatsabermods) server.
