### ISSUE TITLE
map dump returns Service Unavailable

### ISSUE THREAD

**Issue by glg2672** [lolPants/beatsaver-reloaded#79]
## Platform
**This bug report concerns:** *(select all that apply)*
[  ] Client
[X] Server

## Details
**Please describe the problem you are having in as much detail as possible:**
when requesting dump through /api/download/dump/maps the server returns Service Unavailable
## Reproducing the Problem
**Please include detailed steps to reproduce the problem:**
Request https://beatsaver.com/api/download/dump/maps

**Comment by lolPants** [comment]
Not a bug.
