### ISSUE TITLE
Need CORS on API endpoints (/api/maps/detail/{key}) and on CDN images.

### ISSUE THREAD

**Issue by ngokevin** [lolPants/beatsaver-reloaded#8]
## Platform
**This feature request concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
**Please describe the requested feature in as much detail as possible:**
*Note if your feature request is related to a problem.*

Similar to ZIP CORS, but for detail endpoint + images for BeatSaver Viewer.

## Preferred Solution
**Write a clear and concise description of what you want to happen:**

Enable CORS for detail API endpoint (and maybe on most of them), and on the cover images.

**Comment by lolPants** [comment]
CORS should already be enabled for cover images.
I'll get CORS on the API tomorrow
