### ISSUE TITLE
Increased Zip size

### ISSUE THREAD

**Issue by unqltango** [lolPants/beatsaver-reloaded#82]
## Platform
**This feature request concerns:** *(select all that apply)*
- [x] Client
- [x] Server

(I don't know where is the size restriction check, so might be either or both).

## Details
**Please describe the requested feature in as much detail as possible:**
*Note if your feature request is related to a problem.*

I am working on a big map (Nightwish has VERY long songs). The zip is almost 26MB even with best compression and I didn't even finish it yet (it will be a little bit bigger, when I add lightmap and maybe some other difficulty levels). The song is a normal 192 Kb bitrate one, I don't want to go lower than that, it will sound bad.

Currently I can't upload it as there is a 15 MB file size restriction in place.

## Preferred Solution
**Write a clear and concise description of what you want to happen:**

I wonder if it would be possible to raise the upload size limit to 30 MB.

Thanks for considering.
unqlTango

**Comment by luludotdev** [comment]
The ability to customise upload size is coming in the next major version, but it's redundant as I don't control https://beatsaver.com as clearly documented in this project's README.

I would suggest contacting the people who actually do run it at https://beatsaver.com/contact for more assistance.
