### ISSUE TITLE
Ability to sort searched songs

### ISSUE THREAD

**Issue by Zaneo** [lolPants/beatsaver-reloaded#88]
Is sorting supported on search? If not, are there any plans to support it?

I can see:
https://github.com/lolPants/beatsaver-reloaded/blob/d895e22ac246c1de5c91aa86f904b0c65e61659d/server/src/routes/search.ts#L81

But I'm not well versed enough to know if this is page rank score or actual score (such as user score, or downloads).

**Comment by luludotdev** [comment]
Sorting is based on the `score` value returned from ElasticSearch, which is how well the beatmap matches the search term. There are currently no plans to add additional sorting to searches.
