### ISSUE TITLE
Never got a verification Email

### ISSUE THREAD

**Issue by Unusual-Danger** [lolPants/beatsaver-reloaded#95]
This could be  something wrong with the system but when I try to upload a beat map. It says that I must verify myself by an email. I looked around and waited a few days but never got the email. Can this be manually resolved?

**Comment by luludotdev** [comment]
![image](https://user-images.githubusercontent.com/2358182/96707383-b30a9b80-138f-11eb-89ec-808647898b73.png)

Contact the people who run beatsaver.com
