### ISSUE TITLE
Hosting BeatSaver mirrors

### ISSUE THREAD

**Issue by ChipWolf** [lolPants/beatsaver-reloaded#96]
## Platform
**This feature request concerns:** *(select all that apply)*
- [ ] Client
- [x] Server

## Details
**Please describe the requested feature in as much detail as possible:**
*Note if your feature request is related to a problem.*
A method to facilitate mirrors of BeatSaver - similar to artifact repositories for package managers - to potentially improve the availability and resiliency of the service.
This would allow the community to contribute physical resources to BeatSaver.

**Comment by EddwardR** [comment]
Decent idea in theory. Distributing the load to help out in a way. Maybe via some kind of limited rollout though, as to not let any bad actors have that much power.
