### ISSUE TITLE
most songs timeout on download

### ISSUE THREAD

**Issue by okawo80085** [lolPants/beatsaver-reloaded#97]
## Platform
**This bug report concerns:**
- [ ] Client
- [x] Server

## Details
**Please describe the problem you are having in as much detail as possible:**
8/10 songs will timeout on download, here is just one of them
affects both direct and key links

## Reproducing the Problem
**Please include detailed steps to reproduce the problem:**
try to download the aforementioned song(if this is not fixed by the time you're reading this you should get either a timeout or a glorious download speed of 0 kb/s)
[the song](https://beatsaver.com/beatmap/3d1)
this song's download links:
[direct_link](https://beatsaver.com/cdn/3d1/e09a8928b62a1b4bf4c3db3d0307a00a6aee7698.zip)
[key_link](https://beatsaver.com/api/download/key/3d1)

## Further Detail
here is a screenshot of it
![img](https://cdn.discordapp.com/attachments/545923190334160906/785522245296455761/unknown.png)

apart from the song download part, the rest of the api feels a bit slow

this also affects OneClick™ install, BeatSaverDownloader, and/or anything that uses beat saver api to download songs
here are a few songs that work right now:
https://beatsaver.com/beatmap/11b7a
https://beatsaver.com/beatmap/11bbc
https://beatsaver.com/beatmap/11baf
https://beatsaver.com/beatmap/18cc

out of about 40 i tried i was able to download 5

#96 could be a solution to this, among other things

**Comment by luludotdev** [comment]
![image](https://user-images.githubusercontent.com/2358182/96707383-b30a9b80-138f-11eb-89ec-808647898b73.png)

Contact the people who run beatsaver.com

**Comment by okawo80085** [comment]
k thx
