### ISSUE TITLE
Verification URL doesn't send

### ISSUE THREAD

**Issue by Isoware** [lolPants/beatsaver-reloaded#99]
## Platform
- [ ] Client
- [x] Server

## Details
I created a new account, but the mail doesn't show up, neither in spam or normal box.
I tried again, it worked with a gmail.com address, looks like the problem is from hotmail.fr

## Reproducing the Problem
Create an account with hotmail.fr address.

**Comment by nolanblew** [comment]
Same, and around the same time today as this issue was created. I have a hotmail.com address
